//
//  MainpagePresenter.swift
//  NeverGiveUpBTC
//
//  Created by Paul on 14/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainpagePresentationLogic
{
    func presentFetchedBTCData(response: Mainpage.FetchBTCData.Response)
    func presentGetBTCSelect(response: Mainpage.GetDataSelect.Response)
    func presentCalAmountBTC(response: Mainpage.CalAmountBTC.Response)
}

class MainpagePresenter: MainpagePresentationLogic
{
  weak var viewController: MainpageDisplayLogic?
  
  // MARK: Do something
  
    func presentFetchedBTCData(response: Mainpage.FetchBTCData.Response) {
        let viewModel = Mainpage.FetchBTCData.ViewModel(value: response.value, historyBTC: response.historyBTC)
        viewController?.displayFetchedBTCData(viewModel: viewModel)
    }
    
    func presentGetBTCSelect(response: Mainpage.GetDataSelect.Response) {
        let viewModel = Mainpage.GetDataSelect.ViewModel(btcSelect: response.btcSelect)
        viewController?.displayGetBTCSelect(viewModel: viewModel)
    }
    
    func presentCalAmountBTC(response: Mainpage.CalAmountBTC.Response) {
        let viewModel = Mainpage.CalAmountBTC.ViewModel(totalAmount: response.totalAmount)
        viewController?.displayCalAmountBTC(viewModel: viewModel)
    }
    
}
