//
//  MainpageModels.swift
//  NeverGiveUpBTC
//
//  Created by Paul on 14/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Mainpage
{
  // MARK: Use cases
  
    enum FetchBTCData {
        
        struct Request {
            
        }
        
        struct Response {
            var value: BTCModel.Value
            var historyBTC: [BTCModel]
        }
        
        struct ViewModel {
            var value: BTCModel.Value
            var historyBTC: [BTCModel]
        }
    }
    
    enum GetDataSelect {
        
        struct Request {
            var index: Int
        }
        
        struct Response {
            var btcSelect: BTCModel.BPIData
        }
        
        struct ViewModel {
            var btcSelect: BTCModel.BPIData
        }
    }
    
    enum CalAmountBTC {
        
        struct Request {
            var btcSelect: BTCModel.BPIData
            var amount: String
        }
        
        struct Response {
            var totalAmount: String
        }
        
        struct ViewModel {
            var totalAmount: String
        }
    }
    
    enum GenFibonacci {
        
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
}
