//
//  MainpageRouter.swift
//  NeverGiveUpBTC
//
//  Created by Paul on 14/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainpageRoutingLogic
{
    
}

protocol MainpageDataPassing
{
  var dataStore: MainpageDataStore? { get }
}

class MainpageRouter: NSObject, MainpageRoutingLogic, MainpageDataPassing
{
  weak var viewController: MainpageViewController?
  var dataStore: MainpageDataStore?
  
  // MARK: Routing



  // MARK: Navigation
  

  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: MainpageDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
